[package]
name = "quinn"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
rand = "0.4"
rustls = { git = "https://github.com/ctz/rustls", branch = "master" }
webpki = "0.18.0-alpha"
webpki-roots = "0.14"
