[package]
name = "quinn"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
rand = "0.4"
rustls = { path = "../rustls" }
webpki = "0.18.0-alpha"
webpki-roots = "0.14"
