[package]
name = "quinn"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
bytes = "0.4.7"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
log = "0.4"
tokio-udp = "0.1"
rand = "0.4"
ring = "0.13.0-alpha"
rustls = { path = "../rustls", features = ["quic"] }
webpki = "0.18.0-alpha"
webpki-roots = "0.14"

[dev-dependencies]
env_logger = "0.5"
tokio = "0.1"
untrusted = "0.6"
