[package]
name = "quicr"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]

[dependencies]
rand = "0.4"
slab = "0.4"
bytes = "0.4.6"
serde = "1"
serde_derive = "1"
byteorder = "1.1"
failure = "0.1"
digest = "0.7"
blake2 = "0.7"
constant_time_eq = "0.1"
bincode = "0.9"
lazy_static = "1"
slog = { version = "2.1", features = ["max_level_trace", "release_max_level_info"] }
arrayvec = "0.4.7"
fnv = "1.0.6"
openssl = { version = "0.10.6", features = ["v111"] }

[dev-dependencies]
slog-term = "2"
assert_matches = "1.1"
hex-literal = "0.1.1"
