[package]
name = "quicr"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/Ralith/quicr"
description = "QUIC transport protocol implementation for Tokio"
keywords = ["quic"]
categories = [ "network-programming", "asynchronous" ]

[badges]
maintenance = { status = "experimental" }

[dependencies]
quicr-core = { path = ".." }
tokio-reactor = "0.1.1"
tokio-udp = "0.1"
tokio-io = "0.1"
tokio-timer = "0.2.1"
slog = "2.1"
futures = "0.1.21"
fnv = "1.0.6"
openssl = "0.10.6"
failure = "0.1"
bytes = "0.4.6"

[dev-dependencies]
tokio = "0.1.5"
slog-term = "2"
rand = "0.4"
url = "1.7"
